name: Google Assistant Triggered Workflow

on:
  repository_dispatch:
    types: [google_assistant_trigger]

jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Message
        run: echo "Workflow triggered by Google Assistant"